/*
 *  orderIdeals.h 
 *
 *  Copyright (C) 2012 Thomas Kahle
 *  <thomas-kahle@gmx.de>
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 2 of the License, or (at
 *  your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License along
 *  with this program; if not, write to the Free Software Foundation, Inc.,
 *  59 Temple Place, Suite 330, Boston, MA 02111-1307 USA.
 *
 * ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 */
#ifndef ORDERIDEALS_H
#define ORDERIDEALS_H

#include <vector>

#include "monomial.h"
#include "graphbinomial.h"

using namespace std;

// List all monomials dividing a given list of monomials:
vector<Monomial*>* listBelow (const std::vector<Monomial*>& mons); 

// List all monomials in a given degree and number of variables
vector<Monomial*>* allMonomials (const int degree, const int numvars);

// Compute the h-Vector (f-vector) of a pure order ideals generated by monomials
vector<int> hVector (const vector<Monomial*>& mons);

// Enumerate all pure O sequences in given degree, type, and number of variables
vector < vector<int> > enumeratePureOSequences (const int degree, const int type, const int numvars);

// Test if a given sequence is a pure O sequence
// This function basically enumerates, but it uses various shortcuts and is thus faster
bool isPureOSequence (const vector<int>& candidate);

// List all order ideals giving an h vector
void listOrderIdeals (const int degree, const int type, const int numvars, const vector<int>& hV);

// The following are a couple of more experimental functions

// Enumerate pure O-sequences that come out of Alex' Constantinescu's recipe
// for a given complication vector a
vector< vector<int> > testAlexRecipe(const vector<int>& a, 
				     const int rank, 
				     const int type, 
				     const bool permute=0);

// Check Alex' Constantinescu's recipe with the shortcuts from isPureOSequnce
bool isPureOSequenceAlexRecipe(const vector<int>& a, 
			       const int rank, 
			       const int type, 
			       const vector<int>& candidate, 
			       const bool permute=0);

// Compute the difference vector
vector<int> differenceVector (const vector<int>& h);

// Test Conjecture 3.1 in Ha, Stokes, Zanello:
void testAdditivityConjecture (const int degree, const int type, const int numvars);

#endif
